import {roleAllAttribute} from '../dto/storageDtos'
import {Occupation,IsLong,AttentionPosition,Camp,Update} from '../enum/baseEnum'
import {roleName} from '../enum/Chinese'


export const ZANGYIN:roleAllAttribute = {
        "name":roleName.ZANGYIN,
        "range":4,
        "hp":11671,
        "attack":460,
        "power":666,
        "physicalDefense":216,
        "powerDefense":216,
        "attackSpeed":140,
        "criticalHitRate":12,
        "criticalDamage":50,
        "physicalPenetration":314,
        "powerPenetration":314,
        "dodge":5,
        "regeneration":364,
        "rapidly":1000,
        "resistance":0,
        "reflexive":0,
        "damageIncrease":0,
        "damageReduce":0,
        "treatment":0,
        "speed":100,
        "powerIncrease":0,
        "physcialIncrease":0,
        "skillIncrease":0,
        "attackIncrease":0,
        "powerReduce":0,
        "physcialReduce":0,
        "skillReduce":0,
        "attackReduce":0,
        "byTreatment":0,
        "attackRecovery":0,
        "recovery5":0,
        "occupation":Occupation.SHOOTER,
        "isLong":IsLong.LONG,
        "attentionPosition":AttentionPosition.FRIEND,
        "camp":Camp.CYBER_MEDIA,
        "update":Update.ZERO
}

export const KURO:roleAllAttribute = {
    "name":roleName.KURO,
    "range":4,
    "hp":11671,
    "attack":460,
    "power":666,
    "physicalDefense":216,
    "powerDefense":216,
    "attackSpeed":140,
    "criticalHitRate":12,
    "criticalDamage":50,
    "physicalPenetration":314,
    "powerPenetration":314,
    "dodge":5,
    "regeneration":364,
    "rapidly":1000,
    "resistance":0,
    "reflexive":0,
    "damageIncrease":0,
    "damageReduce":0,
    "treatment":0,
    "speed":100,
    "powerIncrease":0,
    "physcialIncrease":0,
    "skillIncrease":0,
    "attackIncrease":0,
    "powerReduce":0,
    "physcialReduce":0,
    "skillReduce":0,
    "attackReduce":0,
    "byTreatment":0,
    "attackRecovery":0,
    "recovery5":0,
    "occupation":Occupation.SHOOTER,
    "isLong":IsLong.LONG,
    "attentionPosition":AttentionPosition.FRIEND,
    "camp":Camp.CYBER_MEDIA,
    "update":Update.ZERO
}