import { AttributeAddObj } from '../dto/storageDtos'
import { RoleNumberAttribute } from '../enum/baseEnum'
import { AddOrPerAdd } from '../enum/operation'


// 职业科技树加成
export const GUARD:Array<AttributeAddObj> =[
    { 
        "attribute":RoleNumberAttribute.HP,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":1200
    },
    { 
        "attribute":RoleNumberAttribute.PHYSICAL_DEFENSE,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":31
    },
    { 
        "attribute":RoleNumberAttribute.RESISTANCE,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":150
    },
    { 
        "attribute":RoleNumberAttribute.POWER_DEFENSE,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":31
    },
    { 
        "attribute":RoleNumberAttribute.HP,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":21
    },
    { 
        "attribute":RoleNumberAttribute.RAPIDLY,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":20
    },
    { 
        "attribute":RoleNumberAttribute.PHYSICAL_DEFENSE,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":21
    },
    { 
        "attribute":RoleNumberAttribute.POWER_DEFENSE,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":21
    },
]

export const SHOOTER:Array<AttributeAddObj> =[
    { 
        "attribute":RoleNumberAttribute.ATTACK,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":38
    },
    { 
        "attribute":RoleNumberAttribute.CRITICAL_HIT_RATE,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":9
    },
    { 
        "attribute":RoleNumberAttribute.POWER,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":38
    },
    { 
        "attribute":RoleNumberAttribute.PHYSICAL_PENETRATION,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":65
    },
    { 
        "attribute":RoleNumberAttribute.CRITICAL_DAMAGE,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":18
    },
    { 
        "attribute":RoleNumberAttribute.ATTACK,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":22
    },
    { 
        "attribute":RoleNumberAttribute.POWER,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":22
    },
    { 
        "attribute":RoleNumberAttribute.PHYSICAL_PENETRATION,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":7
    },
]

export const FIGHTER:Array<AttributeAddObj> =[
    { 
        "attribute":RoleNumberAttribute.ATTACK,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":38
    },
    { 
        "attribute":RoleNumberAttribute.RESISTANCE,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":150
    },
    { 
        "attribute":RoleNumberAttribute.POWER,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":38
    },
    { 
        "attribute":RoleNumberAttribute.HP,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":1200
    },
    { 
        "attribute":RoleNumberAttribute.CRITICAL_HIT_RATE,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":9
    },
    { 
        "attribute":RoleNumberAttribute.ATTACK,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":22
    },
    { 
        "attribute":RoleNumberAttribute.POWER,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":22
    },
    { 
        "attribute":RoleNumberAttribute.HP,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":21
    },
]

export const SPECIAL:Array<AttributeAddObj> =[
    { 
        "attribute":RoleNumberAttribute.ATTACK,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":38
    },
    { 
        "attribute":RoleNumberAttribute.RAPIDLY,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":25
    },
    { 
        "attribute":RoleNumberAttribute.POWER,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":38
    },
    { 
        "attribute":RoleNumberAttribute.HP,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":1200
    },
    { 
        "attribute":RoleNumberAttribute.ATTACK,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":22
    },
    { 
        "attribute":RoleNumberAttribute.POWER,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":22
    },
    { 
        "attribute":RoleNumberAttribute.HP,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":21
    },
]

export const PHYSICIAN:Array<AttributeAddObj> =[
    { 
        "attribute":RoleNumberAttribute.POWER,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":38
    },
    { 
        "attribute":RoleNumberAttribute.RAPIDLY,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":15
    },
    { 
        "attribute":RoleNumberAttribute.PHYSICAL_DEFENSE,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":31
    },
    { 
        "attribute":RoleNumberAttribute.TREATMENT,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":9
    },
    { 
        "attribute":RoleNumberAttribute.POWER_DEFENSE,
        "increaseMethod":AddOrPerAdd.ADD,
        "value":31
    },
    { 
        "attribute":RoleNumberAttribute.POWER,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":22
    },
    { 
        "attribute":RoleNumberAttribute.PHYSICAL_DEFENSE,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":21
    },
    { 
        "attribute":RoleNumberAttribute.POWER_DEFENSE,
        "increaseMethod":AddOrPerAdd.PRECENTAGE,
        "value":21
    },
]